site_name: "Snakemake Benchmark Analyzer"

repo_url: https://github.com/natir/snakemake_ba

theme:
  name: "material"

nav:
  - Home: index.md
  - References:
      - parser.md
      - plot.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
          - https://pandas.pydata.org/docs/objects.inv
        rendering:
          show_source: false
        selection:
          docstring_style: google

    watch:
      - ../snakemake_ba
