name: tests

on:
  pull_request:
    banches: ["**"]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v1

      - name: set Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: '3.10'
          enable-pep582: true

      - name: install dependencies
        run: pdm install -v -Gdtest

      - name: run test
        run: pdm run test
