name: publish_docs

on:
  push:
    branches:
      - main

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material mkdocstrings
      - run: pip install -e .
      - run: cd docs && mkdocs gh-deploy --force
